version: '3.8'

services:
  node_backend:
    container_name: node_backend
    image: node:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=xavierfabregat
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=react-native-todo
    depends_on:
      - postgres
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=xavierfabregat
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=react-native-todo
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
    restart: always

volumes:
  data: {}